---
apiVersion: v2
name: ingress
version: 0.0.1
dependencies:
  - name: ingress-nginx
    version: 4.1.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: dev.enabled
    alias: dev
  - name: ingress-nginx
    version: 4.1.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: prd.enabled
    alias: prd