---
apiVersion: v2
name: ingress
version: 0.0.1
dependencies:
  - name: ingress-nginx
    version: 4.1.4
    repository: https://kubernetes.github.io/ingress-nginx
    condition: enabled.ingress-nginx-dev
    alias: ingress-nginx-dev

  - name: ingress-nginx
    version: 4.1.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: enabled.ingress-nginx-prd
    alias: ingress-nginx-prd
