---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: react-tls
spec:
  dnsNames:
    - gcfr.xyz
  secretName: react-tls
  issuerRef:
    name: letsencrypt-clusterissuer
    kind: ClusterIssuer
