---
name: gcfr-gke-cluster
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
    paths:
      - infra/**
  pull_request:
    branches:
      - main
    paths:
      - infra/**
permissions:
  pull-requests: write
  contents: read

jobs:
  gcaPlan:
    uses: g14com0/actions-template/.github/workflows/plan.yml@main
    with:
      environment: gcfr
      pathToPlan: infra/gca
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

  gkePlan:
    uses: g14com0/actions-template/.github/workflows/plan.yml@main
    with:
      environment: gcfr
      pathToPlan: infra/gke
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

  gcaApply:
    uses: g14com0/actions-template/.github/workflows/apply.yml@main
    needs: [gkePlan, gcaPlan]
    with:
      environment: gcfr
      pathToApply: infra/gca
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

  gkeApply:
    uses: g14com0/actions-template/.github/workflows/apply.yml@main
    needs: [gcaApply]
    with:
      environment: gcfr
      pathToApply: infra/gke
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

  gkeDestroy:
    uses: g14com0/actions-template/.github/workflows/destroy.yml@main
    needs: [gkeApply]
    with:
      environment: gcfr
      pathToDestroy: infra/gke
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
