name: gcfr-sample-reactapp
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

    - name: get-credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: gcfr
        location: europe-west3

    - name: Helm download
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: ingress install
      run: |
        helm dependency update applications/sample-react-app/
        helm upgrade -i -f applications/sample-react-app/values.yaml sample-reactapp applications/sample-react-app
