name: gcfr-certmanager
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

    - name: get-credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: gcfr
        location: europe-west3

    - name: Helm download
      run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: certmanager install
      run: |
        
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.crds.yaml

        helm dependency update applications/cert-manager/
        helm upgrade -i --create-namespace --namespace cert-manager -f applications/cert-manager/values.yaml cert-manager applications/cert-manager
